.PHONY: clean All

All:
	@echo "----------Building project:[ p2 - Debug ]----------"
	@cd "p2" && "$(MAKE)" -f  "p2.mk"
clean:
	@echo "----------Cleaning project:[ p2 - Debug ]----------"
	@cd "p2" && "$(MAKE)" -f  "p2.mk" clean
